### ISSUE TITLE
Compiling problem with newer c++: base58 prefixes

### ISSUE THREAD

**Issue by beralt85** [SilkNetwork/Silk-Core#16]
Hello,

When compiling from source, make exits with
` error: ambiguous overload for ‘operator=’`

Doing some research, I found that this was related to (the use of non-standard) prefixes.
I fixed the problem by changing `src/chainparams.cpp` in analogy to:
https://github.com/bitcoin/bitcoin/commit/a2b04ddfe6452e7d6274f4096bf3f2aee695a6d9

I am not a dev, so sorry I can't say more. 

I am on Arch Linux, with `libc++ 3.8.0-1` and `boost 1.61.0-2`

**Comment by spencerlievens** [comment]
Yes this is a known issue with Arch Linux. Will complete this work, test (for testings sake) and then merge.

**Comment by spencerlievens** [comment]
https://github.com/SilkNetwork/Silk-Core/pull/21
