### ISSUE TITLE
Need to add a single hard coded seed node for DNS seeder discovery

### ISSUE THREAD

**Issue by GregoryBetz** [SilkNetwork/Silk-Core#18]
### Describe the issue
The Seeders seem to disregard a wallet with no conf and no addnodes added. Once you add a node then the DNS seeder kicks in and populates your peers.dat with it's nodes.  I'm not sure if there is a better fix for this problem than one hard coded node,, but I know that would fix the issue.
### Steps to reproduce
1. Clear Silk data directory
2. Start wallet with no conf or addnodes.
3. DNS does not pick up the slack.

### Expected behavior
Tell us what should happen
The seeder should populate your client with as many peers as possible.
### Actual behavior
Tell us what happens instead
It seems the wallet is disregardfed as an anomoly with 0 connections and the seeder ignores it.

Perhaps this could be solved in the seeder itself by changing something. Adding a permanent node would fix the issue on the client side though and is straightforward.
### What platform are you using (Linux, Windows, Mac)

Ubuntu 16.04 LTS 64 bit
Windows 10 64 bit

**Comment by GregoryBetz** [comment]
Yes this was with no conf. I added a node through the console.

**Comment by spencerlievens** [comment]
Closing as not relevant.
