### ISSUE TITLE
silk.conf creation on first start

### ISSUE THREAD

**Issue by spencerlievens** [SilkNetwork/Silk-Core#20]
### Describe the issue
Currently users need to create a conf file for Silk and sometimes users will save the file in the wrong format so the wallet cannot read the information to configure the wallet correctly.

### Steps to reproduce
1. Make an incompatible silk.conf
2. Start wallet

### Expected behavior
On start of wallet a silk.conf file should be generated with rpcuser, rpcpassword, rpcport as a minimum to allow first start and also ensure the file is able to be read by the wallet after a user potentially edits and adds flags.

### Actual behavior
Daemon will not start without silk.conf, Qt will start without but with default configuration.

**Comment by AmirAbrams** [comment]
PR #32  and #34 resolve this issue.
