### ISSUE TITLE
Memory Use Calculation Incorrect

### ISSUE THREAD

**Issue by AmirAbrams** [SilkNetwork/Silk-Core#26]
### Describe the issue
In the debug console, the memory use display is incorrect
>  Memory Usage:  133808137.23 megabytes

### Steps to reproduce
1. Open Qt Wallet
2. Open Tools Windows (Console) and navigate to the first tab ("Information")
3. Watch the Memory Pool Memory Use value

### Expected behavior
Tell us what should happen
* It should show the correct memory use

### What platform are you using (Linux, Windows, Mac)
Ubuntu Linux 16.04 64-bit

**Comment by spencerlievens** [comment]
Showing in bytes instead of megabytes?

**Comment by AmirAbrams** [comment]
PR #31 should fix this issue.  Please test.

**Comment by spencerlievens** [comment]
I have 0 funds to generate tx's.

**Comment by spencerlievens** [comment]
utACK

**Comment by GregoryBetz** [comment]
Tested ACK

Closing.
