### ISSUE TITLE
Remove `listen=1` from auto-generated `silk.conf`

### ISSUE THREAD

**Issue by beralt85** [SilkNetwork/Silk-Core#46]
### Description
Starting `silkd -daemon` for the first time on a new install, auto-generates `~/.silk/silk.conf` with an entry `listen=1`. Silkd then exits with an error message.

### Steps to reproduce
1. Fresh install
2.  `silkd -daemon`

### Suggested solution
Change this option in the auto-generated `silk.conf`

**Comment by spencerlievens** [comment]
Fixed with https://github.com/SilkNetwork/Silk-Core/pull/47
