### ISSUE TITLE
Send Transaction button on the Spend Funds ui page

### ISSUE THREAD

**Issue by GregoryBetz** [SilkNetwork/Silk-Core#50]
### Describe the issue
Send Transaction button on the Spend Funds ui page does not work. The add input button does not seem to do anything either. Is this a second sending ui page absolutely necessary anyway?

### Screenshots
![silk_spend_funds](https://cloud.githubusercontent.com/assets/16812903/19232449/d41ba4f6-8ead-11e6-9b98-0039b6b519e3.PNG)

### What platform are you using (Linux, Windows, Mac)
Windows 10 64 bit

**Comment by AmirAbrams** [comment]
Yes, we need this UI to spend multisig funds.  The other option is the command line.  

You first need to select an input on the left side to send a transaction.  You can paste the tx hash in the transaction id text box and it should find it.  Then:

1. Create Transaction
2. Sign Transaction
3. Send Transaction

Usability still needs improvement.
