### ISSUE TITLE
Initial Network dont work at Windows Releases of v1.0.1.0

### ISSUE THREAD

**Issue by PrometheusXDE** [SilkNetwork/Silk-Core#51]
At the Windows version (both 32bit and 64bit) is no connection to the DNS Seeders
So there cant be any connection to the network
But it seems that its not an DNS Seeder problem, i discovered now that the windows
client dont get an external IP
So there will be only connections when the Users add an addnode in the conf file or
with "addnode xx.xxx.xxxx.xxx add" in the debug console
http://img.techpowerup.org/161010/capture040.jpg

I have tryd it with an manual "bind=xx.xx.xx.xx" 
Different port
Turnd IRC on
...
nothing, only adding a addnode helps or an working peers.dat

**Comment by AmirAbrams** [comment]
I can replicate the issue.  Thank you for reporting it.  I will need to re-build the Windows binaries.  They were built before we added @MCDev's DNS seeder node.  It should have the other seeders but I have problems connecting to those.

**Comment by AmirAbrams** [comment]
This issue is resolved in the v1.0.1.1 Windows binaries: [silk-qt v1.0.1.1 for Windows](https://github.com/SilkNetwork/Silk-Core/releases/tag/1.0.1.1)
