### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by AmirAbrams** [SilkNetwork/Silk-Core#56]
### Describe the issue

CPU utilization is 100% on my Linux VM with 2 CPUs.  The silknetwork.net seeders do not work for me and the dnsseeder.com/io/host/net seem to cause this problem.  Others have indicated they can't get nodes from the two silknetwork.net seeders.

The CPU over-utilization also seems to slow down the chain download.  It is still fast but much faster without the CPU issue.
### Expected behavior

CPU usage should be under 1% after the blockchain is fully synchronized.
### Screenshots

Silk-Core Qt v1.0.1.1 (100%):
![Silk High CPU Utilization](https://cloud.githubusercontent.com/assets/7564876/19586533/583593c6-971b-11e6-95fe-372a8ff6e173.png)

Silk-Core Qt v1.0.1.1 without DNS Seeders (0.7%):
![silk-noseeders-cpu_20161020](https://cloud.githubusercontent.com/assets/7564876/19586731/b7a63200-971d-11e6-95ff-c22d24078487.png)
### What platform are you using (Linux, Windows, Mac)

Ubuntu Linux 16.04.  Also see this on Windows 64 & 32 bit v1.0.1.1.

**Comment by spencerlievens** [comment]
I can confirm that I seem to be having similar issues with CPU and with DNSSeeder connectivity. Max peers I have seen on my local wallet is only 6 connections.

**Comment by AmirAbrams** [comment]
@MineChuteDev and I are working on this.

**Comment by GregoryBetz** [comment]
Problem is solved. See details in PR #85
