### ISSUE TITLE
Serious lapses in "make clean" implementation

### ISSUE THREAD

**Issue by empinel** [SilkNetwork/Silk-Core#63]
### Describe the issue

When running the 'make clean' commands, in the process of removing generated files, when removing the generated files in 'build-aux', it clears the entire folder
### Steps to reproduce
1.  Make clean
2.  That's it
3.  Realize you deleted some important stuff!
### Expected behavior

Tell us what should happen

Clearing of `build-aux` remains (unwanted files generated during compilation)
### Actual behavior

Tell us what happens instead

Not what expected, deletes contents of `build-aux` and a WTF expression on the face!
### What platform are you using (Linux, Windows, Mac)

Ubuntu 16.04.01 LTS on VMWare Fusion running on macOS Sierra

**Comment by GregoryBetz** [comment]
Yea I noticed this last night as well.

**Comment by AmirAbrams** [comment]
Testing #84 to see if it resolved the issue.  Will close if it works.
