### ISSUE TITLE
QObject::killTimer(): Error

### ISSUE THREAD

**Issue by AmirAbrams** [SilkNetwork/Silk-Core#7]
### Describe the issue
Qt timer object not disposed:
`GUI: QObject::killTimer(): Error: timer id 15 is not valid for object 0x35b9170 (OverviewPage, OverviewPage), timer has not been killed`

### Steps to reproduce
1. Open Qt wallet
2. Shutdown Qt wallet
3. Check debug.log

**Comment by AmirAbrams** [comment]
This PR should fix the error:  https://github.com/SilkNetwork/Silk-Core/pull/10
#10

**Comment by spencerlievens** [comment]
Was this confirmed fix with your PR @AmirAbrams
