### ISSUE TITLE
New installation - conf file incorrectly written

### ISSUE THREAD

**Issue by MineChuteDev** [SilkNetwork/Silk-Core#74]
### Describe the issue
When creating the silk.conf file on a new insall, port 16662 is incorrectly being written as rpcport

### Steps to reproduce
Start new instance of silk-qt

### Expected behavior
silk.conf file should contain port=16662

### Actual behavior
silk.conf file contains rpcport=16662

### Screenshots

![conf file issue](https://cloud.githubusercontent.com/assets/15707788/19627478/6d6fc530-9915-11e6-9510-68c04db91a7b.PNG)

### What platform are you using (Linux, Windows, Mac)
Ubuntu 16.04
Debain 8.6

**Comment by AmirAbrams** [comment]
The RPC port should be 16663 and the P2P port is 16662.  Good catch.
```
/**
 * Main network
 */
class CBaseMainParams : public CBaseChainParams
{
public:
    CBaseMainParams()
    {
        networkID = CBaseChainParams::MAIN;
        nRPCPort = 16663;
    }
};
```

**Comment by AmirAbrams** [comment]
PR #76 should fix this one.  Thanks again!

**Comment by AmirAbrams** [comment]
PR #76 merged.  Closing this issue.
